//! NSEvent — user-input and system events.

use crate::runtime::*;

/// Event types.
#[repr(u64)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum NSEventType {
    LeftMouseDown = 1,
    LeftMouseUp = 2,
    RightMouseDown = 3,
    RightMouseUp = 4,
    MouseMoved = 5,
    LeftMouseDragged = 6,
    RightMouseDragged = 7,
    MouseEntered = 8,
    MouseExited = 9,
    KeyDown = 10,
    KeyUp = 11,
    FlagsChanged = 12,
    AppKitDefined = 13,
    SystemDefined = 14,
    ApplicationDefined = 15,
    Periodic = 16,
    CursorUpdate = 17,
    ScrollWheel = 22,
    TabletPoint = 23,
    TabletProximity = 24,
    OtherMouseDown = 25,
    OtherMouseUp = 26,
    OtherMouseDragged = 27,
}

/// Modifier flags bitflags.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
pub struct ModifierFlags(pub NSUInteger);

impl ModifierFlags {
    pub const SHIFT: Self = Self(1 << 17);
    pub const CONTROL: Self = Self(1 << 18);
    pub const OPTION: Self = Self(1 << 19);
    pub const COMMAND: Self = Self(1 << 20);

    /// Check whether a specific flag is set.
    pub fn contains(self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }
}

impl std::ops::BitOr for ModifierFlags {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self {
        Self(self.0 | rhs.0)
    }
}

impl std::ops::BitAnd for ModifierFlags {
    type Output = Self;
    fn bitand(self, rhs: Self) -> Self {
        Self(self.0 & rhs.0)
    }
}

/// An event.
pub struct NSEvent(pub(super) Id);

impl NSEvent {
    /// Return the raw ObjC pointer (does not transfer ownership).
    pub fn as_raw(&self) -> Id {
        self.0
    }

    /// Get the event type.
    pub fn event_type(&self) -> NSEventType {
        unsafe {
            let raw: u64 = msg_send!(self.0, sel!("type"), fn(Id, Sel) -> u64);
            std::mem::transmute(raw)
        }
    }

    /// Get the location in the event's window coordinates.
    pub fn location_in_window(&self) -> CGPoint {
        unsafe {
            msg_send!(self.0, sel!("locationInWindow"), fn(Id, Sel) -> CGPoint)
        }
    }

    /// Get the modifier flags.
    pub fn modifier_flags(&self) -> ModifierFlags {
        unsafe {
            let raw: NSUInteger = msg_send!(
                self.0,
                sel!("modifierFlags"),
                fn(Id, Sel) -> NSUInteger
            );
            ModifierFlags(raw)
        }
    }

    /// Get the key code for keyboard events.
    pub fn key_code(&self) -> u16 {
        unsafe {
            msg_send!(self.0, sel!("keyCode"), fn(Id, Sel) -> u16)
        }
    }

    /// Get the characters generated by the event.
    pub fn characters(&self) -> String {
        unsafe {
            let ns: Id = msg_send!(self.0, sel!("characters"), fn(Id, Sel) -> Id);
            from_nsstring(ns)
        }
    }

    /// Get the characters ignoring modifiers.
    pub fn characters_ignoring_modifiers(&self) -> String {
        unsafe {
            let ns: Id = msg_send!(
                self.0,
                sel!("charactersIgnoringModifiers"),
                fn(Id, Sel) -> Id
            );
            from_nsstring(ns)
        }
    }

    /// Check whether this is a key repeat.
    pub fn is_a_repeat(&self) -> bool {
        unsafe {
            to_bool(msg_send!(self.0, sel!("isARepeat"), fn(Id, Sel) -> BOOL))
        }
    }

    /// Get the horizontal scroll delta.
    pub fn delta_x(&self) -> CGFloat {
        unsafe {
            msg_send!(self.0, sel!("deltaX"), fn(Id, Sel) -> CGFloat)
        }
    }

    /// Get the vertical scroll delta.
    pub fn delta_y(&self) -> CGFloat {
        unsafe {
            msg_send!(self.0, sel!("deltaY"), fn(Id, Sel) -> CGFloat)
        }
    }

    /// Get the precise horizontal scrolling delta.
    pub fn scrolling_delta_x(&self) -> CGFloat {
        unsafe {
            msg_send!(self.0, sel!("scrollingDeltaX"), fn(Id, Sel) -> CGFloat)
        }
    }

    /// Get the precise vertical scrolling delta.
    pub fn scrolling_delta_y(&self) -> CGFloat {
        unsafe {
            msg_send!(self.0, sel!("scrollingDeltaY"), fn(Id, Sel) -> CGFloat)
        }
    }

    /// Get the button number.
    pub fn button_number(&self) -> i64 {
        unsafe {
            msg_send!(self.0, sel!("buttonNumber"), fn(Id, Sel) -> i64)
        }
    }

    /// Get the click count.
    pub fn click_count(&self) -> i64 {
        unsafe {
            msg_send!(self.0, sel!("clickCount"), fn(Id, Sel) -> i64)
        }
    }

    /// Get the window associated with this event, if any.
    pub fn window(&self) -> Option<super::window::NSWindow> {
        unsafe {
            let raw: Id = msg_send!(self.0, sel!("window"), fn(Id, Sel) -> Id);
            if raw.is_null() {
                None
            } else {
                Some(super::window::NSWindow(retain(raw)))
            }
        }
    }

    /// Get the event timestamp.
    pub fn timestamp(&self) -> f64 {
        unsafe {
            msg_send!(self.0, sel!("timestamp"), fn(Id, Sel) -> f64)
        }
    }
}

impl Clone for NSEvent {
    fn clone(&self) -> Self {
        Self(unsafe { retain(self.0) })
    }
}

impl Drop for NSEvent {
    fn drop(&mut self) {
        unsafe { release(self.0) }
    }
}
